/*
* Generated file
*
* Generated from: yang module name: bootstrapping-impl yang module local name: bootstrapping-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jun 07 10:26:41 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.point.bootstrapping.impl;
public class BootstrappingModuleFactory extends eu.point.bootstrapping.impl.AbstractBootstrappingModuleFactory {

}
