/*
* Generated file
*
* Generated from: yang module name: registry-impl yang module local name: registry-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Oct 20 12:01:36 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.point.registry.impl;
public class RegistryModuleFactory extends eu.point.registry.impl.AbstractRegistryModuleFactory {

}
