/*
* Generated file
*
* Generated from: yang module name: monitoring-impl yang module local name: monitoring-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 27 20:25:16 EEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.point.monitoring.impl;
public class MonitoringModuleFactory extends eu.point.monitoring.impl.AbstractMonitoringModuleFactory {

}
