/*
 * enumerations.hh
 *
 *  Created on: 9 Feb 2016
 *      Author: Sebastian Robitzsch <sebastian.robitzsch@interdigital.com>
 *
 * This file is part of the ICN application MOnitOring SErver (MOOSE) which
 * comes with Blackadder.
 *
 * MOOSE is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * MOOSE is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * MOOSE. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef APPS_MONITORING_SERVER_ENUMERATIONS_HH_
#define APPS_MONITORING_SERVER_ENUMERATIONS_HH_

#include <blackadder_enums.hpp>
#include <moly/enum.hh>

/*!
 * \brief Enumeration for VIDA. DO NOT CHANGE THE ORDER!
 */
enum attribute_t
{
	ATTRIBUTE_UNKNOWN,
	ATTRIBUTE_GW_LIST_OF_FQDNS,/*!< 1 */
	ATTRIBUTE_GW_PREFIXES,/*!< 2 */
	ATTRIBUTE_GW_HTTP_REQUESTS,/*!< 3 */
	ATTRIBUTE_GW_HTTP_REQ_RES_RATIO,/*!< 4 */
	ATTRIBUTE_GW_INCOMING_BYTES,/*!< 5 */
	ATTRIBUTE_GW_OUTGOING_BYTES,/*!< 6 */
	ATTRIBUTE_GW_STATE,/*!< 7 */
	ATTRIBUTE_FN_NAME,/*!< 8 */
	ATTRIBUTE_FN_LINK_ID,/*!< 9 */
	ATTRIBUTE_FN_STATE,/*!< 10 */
	ATTRIBUTE_NAP_LIST_OF_FQDNS,/*!< 11 */
	ATTRIBUTE_NAP_PREFIXES,/*!< 12 */
	ATTRIBUTE_NAP_HTTP_REQUESTS,/*!< 13 */
	ATTRIBUTE_NAP_HTTP_REQ_RES_RATIO, /*!< 14 CMC group size */
	ATTRIBUTE_NAP_INCOMING_BYTES,/*!< 15 */
	ATTRIBUTE_NAP_OUTGOING_BYTES,/*!< 16 */
	ATTRIBUTE_NAP_STATE,/*!< 17 */
	ATTRIBUTE_RV_NUMBER_OF_STATES,/*!< 18 */
	ATTRIBUTE_RV_NUMBER_OF_MATCH_REQUESTS,/*!< 19 */
	ATTRIBUTE_RV_CPU_LOAD,/*!< 20 */
	ATTRIBUTE_RV_CPU_MEMORY_USAGE,
	ATTRIBUTE_RV_CPU_THREADS,
	ATTRIBUTE_RV_STATE,
	ATTRIBUTE_SV_FQDN,
	ATTRIBUTE_SV_STATE,
	ATTRIBUTE_TM_NUMBER_OF_UNICAST_FIDS,
	ATTRIBUTE_TM_NUMBER_OF_PATH_REQUESTS,
	ATTRIBUTE_TM_AVERAGE_PATH_LENGTH,
	ATTRIBUTE_TM_MIN_PATH_LENGTH,
	ATTRIBUTE_TM_MAX_PATH_LENGTH,/*!< 30 */
	ATTRIBUTE_TM_CPU_LOAD,
	ATTRIBUTE_TM_CPU_MEMORY_USAGE,
	ATTRIBUTE_TM_CPU_THREADS,
	ATTRIBUTE_TM_STATE,
	ATTRIBUTE_UE_NAME,
	ATTRIBUTE_UE_DASH_JITTER,
	ATTRIBUTE_UE_DASH_DROPPED_FRAMES,
	ATTRIBUTE_UE_STATE,
	ATTRIBUTE_LNK_DESTINATIONS,
	ATTRIBUTE_LNK_BYTES_TIME_INTERVAL,/*!< 40 */
	ATTRIBUTE_LNK_STATE,
	ATTRIBUTE_LNK_BUFFER_OCCUPANCY,
	ATTRIBUTE_LNK_BUFFER_FULL_EVENT,
	ATTRIBUTE_NAP_NETWORK_LATENCY,
	ATTRIBUTE_UE_E2E_LATENCY,
	ATTRIBUTE_SV_E2E_LATENCY,
	ATTRIBUTE_GW_NETWORK_LATENCY,
	ATTRIBUTE_FN_CPU_UTILISATION,
	ATTRIBUTE_TM_CPU_UTILISATION,
	ATTRIBUTE_RV_CPU_UTILISATION,/*!< 50 */
	ATTRIBUTE_NAP_CPU_UTILISATION,
	ATTRIBUTE_GW_CPU_UTILISATION,
	ATTRIBUTE_UE_CPU_UTILISATION,
	ATTRIBUTE_SV_CPU_UTILISATION,
	ATTRIBUTE_FN_TX_BYTES_PORT,
	ATTRIBUTE_FN_RX_BYTES_PORT,
	ATTRIBUTE_FN_PACKET_DROP_RATE_PORT,
	ATTRIBUTE_FN_PACKET_ERROR_RATE_PORT,
	ATTRIBUTE_FN_PORT_STATE,
	ATTRIBUTE_NAP_CHANNEL_AQUISITION_TIME,/*!< 60*/
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_IP,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_HTTP,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_COAP,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_MONITORING,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_MANAGEMENT,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_SURROGACY,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_LINK_STATE,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_PATH_MANAGEMENT,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_EXPERIMENTATION,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_IGMP_CTRL,/*!< 70 */
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_IGMP_DATA,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_APP_RV,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_RV_TM,
	ATTRIBUTE_TM_PATH_CALCULATIONS_NAMESPACE_TM_APP,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_IP,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_HTTP,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_COAP,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_MONITORING,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_MANAGEMENT,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_SURROGACY,/*!< 80 */
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_LINK_STATE,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_PATH_MANAGEMENT,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_EXPERIMENTATION,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_IGMP_CTRL,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_IGMP_DATA,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_APP_RV,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_RV_TM,
	ATTRIBUTE_RV_PUBLISHERS_NAMESPACE_TM_APP,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_IP,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_HTTP,/*!< 90 */
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_COAP,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_MONITORING,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_MANAGEMENT,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_SURROGACY,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_LINK_STATE,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_PATH_MANAGEMENT,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_EXPERIMENTATION,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_IGMP_CTRL,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_IGMP_DATA,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_APP_RV,/*!< 100 */
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_RV_TM,
	ATTRIBUTE_RV_SUBSCRIBERS_NAMESPACE_TM_APP,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_IP,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_HTTP,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_COAP,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_MONITORING,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_MANAGEMENT,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_SURROGACY,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_LINK_STATE,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_PATH_MANAGEMENT,/*!< 110 */
	ATTRIBUTE_RV_MATCHES_NAMESPACE_EXPERIMENTATION,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_IGMP_CTRL,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_IGMP_DATA,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_APP_RV,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_RV_TM,
	ATTRIBUTE_RV_MATCHES_NAMESPACE_TM_APP,
	ATTRIBUTE_FN_PACKET_JITTER_CID,
	ATTRIBUTE_NAP_PACKET_JITTER_CID,
	ATTRIBUTE_NAP_RX_BYTES_IPV4_MULTICAST,
	ATTRIBUTE_NAP_RX_BYTES_IPV6_MULTICAST,/*!< 120 */
	ATTRIBUTE_NAP_TX_BYTES_IPV4_MULTICAST,
	ATTRIBUTE_NAP_TX_BYTES_IPV6_MULTICAST,
	ATTRIBUTE_NAP_RX_BYTES_HTTP,
	ATTRIBUTE_NAP_TX_BYTES_HTTP,
	ATTRIBUTE_NAP_RX_BYTES_IP,
	ATTRIBUTE_NAP_TX_BYTES_IP,
	ATTRIBUTE_NAP_BUFFER_SIZE_IP_HANDLER,
	ATTRIBUTE_NAP_BUFFER_SIZE_HTTP_HANDLER_ICN,
	ATTRIBUTE_NAP_BUFFER_SIZE_HTTP_HANDLER_REQUESTS,
	ATTRIBUTE_NAP_BUFFER_SIZE_HTTP_HANDLER_RESPONSES,/*!< 130 */
	ATTRIBUTE_NAP_BUFFER_SIZE_LTP,
	ATTRIBUTE_MOOSE_BUFFER_SIZE_MESSAGE_STACK,
	ATTRIBUTE_NAP_FILE_DESCRIPTOR_TCP
};

enum element_type_t
{
	ELEMENT_TYPE_UNKNOWN,/*0*/
	ELEMENT_TYPE_FN,
	ELEMENT_TYPE_GW,
	ELEMENT_TYPE_MOOSE,
	ELEMENT_TYPE_NAP,
	ELEMENT_TYPE_RV,
	ELEMENT_TYPE_SERVER,
	ELEMENT_TYPE_TM,
	ELEMENT_TYPE_UE,
	/* Combined node types (2) */
	ELEMENT_TYPE_FN_GW,
	ELEMENT_TYPE_FN_MOOSE,/*10*/
	ELEMENT_TYPE_FN_NAP,
	ELEMENT_TYPE_FN_RV,
	ELEMENT_TYPE_FN_TM,
	/* Combined node types (3) */
	ELEMENT_TYPE_FN_GW_MOOSE,
	ELEMENT_TYPE_FN_GW_RV,
	ELEMENT_TYPE_FN_GW_TM,
	ELEMENT_TYPE_FN_MOOSE_NAP,
	ELEMENT_TYPE_FN_MOOSE_RV,
	ELEMENT_TYPE_FN_MOOSE_TM,
	ELEMENT_TYPE_FN_RV_TM,/*20*/
	ELEMENT_TYPE_FN_NAP_TM,
	ELEMENT_TYPE_FN_NAP_RV,
	/* Combined node types (4) */
	ELEMENT_TYPE_FN_GW_MOOSE_RV,
	ELEMENT_TYPE_FN_GW_MOOSE_TM,
	ELEMENT_TYPE_FN_GW_RV_TM,
	ELEMENT_TYPE_FN_MOOSE_NAP_TM,
	ELEMENT_TYPE_FN_MOOSE_NAP_RV,
	ELEMENT_TYPE_FN_MOOSE_RV_TM,
	ELEMENT_TYPE_FN_NAP_RV_TM,
	/* Combined node types (5) */
	ELEMENT_TYPE_FN_GW_MOOSE_RV_TM,/*30*/
	ELEMENT_TYPE_FN_MOOSE_NAP_RV_TM
};
#endif /* APPS_MONITORING_SERVER_ENUMERATIONS_HH_ */
